### ISSUE TITLE
Здравствуйте а есть пример с 1С ?

### ISSUE THREAD

**Issue by Arsiprog** [korv1982/InnovaIT-Asterisk-Native#2]
Здравствуйте а есть пример с 1С ? Шаблон какой ни будь я тут пытаюсь ее завести не получается

**Comment by korv1982** [comment]
Там 2 текстовых файла были приложены. И cf был
--
Отправлено из Mail.ru для Android четверг, 21 сентября 2023г., 18:03 +03:00 от Arsiprog  ***@***.*** :

**Comment by korv1982** [comment]
Добавил выгрузку готовой конфигурации. Можно скачать и там уже все готовое для работы. Единственное, обновите компоненту. Я добавил новый релиз. Никто не жаловался, кроме одного пользователя с утечкой памяти. На моих проектах, где 50-100 человек работает без нареканий.  Но там я так понимаю CALL-цент человек на 500.

**Comment by Arsiprog** [comment]
спасибо большое буду тестить )

**Comment by Arsiprog** [comment]
![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/9af05e84-4d18-4e3a-8927-2c064f97ea12)
Такая ошибка выходит (

**Comment by Arsiprog** [comment]
![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/4d74f979-9599-47b8-af7d-cd1c25825cd2)

**Comment by Arsiprog** [comment]
1С x64

**Comment by korv1982** [comment]
Ключ продукта и идентификатор удалены. Это лишнее теперь. В пул реквесте новые файлы, в которых указаны методы и свойства доступные в компоненте.

**Comment by Arsiprog** [comment]
А все разобрался она немножко думает прежде чем выкинет ошибку большое спасибо бро)

**Comment by Arsiprog** [comment]
Хорошо бы сделать образцы кода расписать и выложить могу на себя взять эти обязательства если есть инфа что расписать оформлю ?

**Comment by korv1982** [comment]
Конфа и так является образцом кода. В фильтрах все расписано. Остальное это документация к астериск

**Comment by Arsiprog** [comment]
Звонок работает проходит через phoner lite

**Comment by Arsiprog** [comment]
а как отправить команду на поднятия звонка ? это тоже astrics ?

**Comment by Arsiprog** [comment]
то есть там событие должно быть которые покажет окно я нажму принять и должен поднять трубку верно же ?

**Comment by Arsiprog** [comment]
Сказать честно это не чего не сказать красавчик ) шас свою звонилку буду делать )

**Comment by korv1982** [comment]
Проекту 8 лет. Это переработанный другой проект. Не помню автора. Здесь добавлены деления на пакеты а так же регулярки. Устранена утечка памяти. Если есть интерес, оформляй пулл реквест. Посмотрю. И если будет действительно нужная информация, добавлю. X64 я бы не рекомендовал использовать. Будут другие проблемы, с другими драйверами. Сам сервер x64 да. Клиенты, нет.

**Comment by Arsiprog** [comment]
тогда вопрос как отловить событие когда мне звонят по функциям прошелся не нашел (

**Comment by Arsiprog** [comment]
> Проекту 8 лет. Это переработанный другой проект. Не помню автора. Здесь добавлены деления на пакеты а так же регулярки. Устранена утечка памяти. Если есть интерес, оформляй пулл реквест. Посмотрю. И если будет действительно нужная информация, добавлю. X64 я бы не рекомендовал использовать. Будут другие проблемы, с другими драйверами. Сам сервер x64 да. Клиенты, нет.
> […](#)
> Хорошо бы сделать образцы кода расписать и выложить могу на себя взять эти обязательства если есть инфа что расписать оформлю ? — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you modified the open/close state. Message ID: @ github . com>

Кароче сделаю интерфейс звонилки выложу и дальше будем разбираться

**Comment by Arsiprog** [comment]
![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/1a2c88be-eb57-4c26-a897-c41c26dd28b1)

**Comment by korv1982** [comment]
Нужно установить регулярное выражение, и включить режим прослушивания. Это все есть в демо базе

**Comment by korv1982** [comment]
В первую очередь читать документацию на астериск. Там есть события входящее соединение, подняли трубку, перенаправление вызова. Это все разные эвенты.

**Comment by korv1982** [comment]
Само событие придет как внешнее событие.

**Comment by Arsiprog** [comment]
ок понял пошел тестить отпишусь)

**Comment by korv1982** [comment]
Не правильно мыслишь.originate  в помощь. Вызов делается средствами 1с путём отправки команды. А софтофон должен уметь сразу снимать трубку.

**Comment by Arsiprog** [comment]
разобрался бро
![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/131014d2-3d04-415e-a84c-ba09911cad18)

нужно заблокать

![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/3784ff95-e326-464b-93c9-2944dbef02d2)

**Comment by Arsiprog** [comment]
подскажи пожалуйста какой код будет для принятия вызова ? Астерикс
По типу этого 
; Номер 102 принял вызов
Event: Newstate
Privilege: call,all
Channel: SIP/102-00000794
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: 102
CallerIDName: device
ConnectedLineNum: 101
ConnectedLineName: Anton Oskin
Uniqueid: 1366383392.2838

**Comment by Arsiprog** [comment]
![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/e2f4db15-ecf9-4791-a350-42c3afacd130)

**Comment by Arsiprog** [comment]
Источник=InnovaIT-Asterisk-Native Событие=Received Данные=Response: Error
Message: Missing action in request 

Такую ошибку кидает когда принять хочу

Завершить я смог 

![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/8925fcdc-79bd-467e-967c-d9a7db43e5fa)

**Comment by korv1982** [comment]
> Источник=InnovaIT-Asterisk-Native Событие=Received Данные=Response: Error Message: Missing action in request
> 
> Такую ошибку кидает когда принять хочу
> 
> Завершить я смог
> 
> ![image](https://user-images.githubusercontent.com/45854657/270098452-8925fcdc-79bd-467e-967c-d9a7db43e5fa.png)

https://docs.asterisk.org/Asterisk_21_Documentation/API_Documentation/AMI_Actions/
http://www.phonerlite.de/cli_en.htm

Но я бы эту задачу решал по другому. Раз используется софтофон. Берем софтофон, который умеет автоматически отвечать на звонок. Все входящие звонки помещаем в очередь. От туда кидаем на 1С событие, в которой указан, кому пришел звонок. При нажатии кнопки поднятия трубки, посылаем команду извлечения из очереди и соединением с номером. Софтофон автоматом поднимает трубку. Эти вопросы не относятся к компоненте. Эта реализация описана на 1001 сайте. Надеюсь, вопросов как работает астериск ко мне не будет. Я не учебный портал.

**Comment by Arsiprog** [comment]
Блин сложно понял спасибо большое ) Вопрос а за доп плату сможете мне помочь допилить ?

**Comment by Arsiprog** [comment]
Мне  не по коду в 1с а по логике все таки я не ас специалист по телефонии (

**Comment by Arsiprog** [comment]
> > Источник=InnovaIT-Asterisk-Native Событие=Received Данные=Response: Error Message: Missing action in request
> > Такую ошибку кидает когда принять хочу
> > Завершить я смог
> > ![image](https://user-images.githubusercontent.com/45854657/270098452-8925fcdc-79bd-467e-967c-d9a7db43e5fa.png)
> 
> https://docs.asterisk.org/Asterisk_21_Documentation/API_Documentation/AMI_Actions/ http://www.phonerlite.de/cli_en.htm
> 
> Но я бы эту задачу решал по другому. Раз используется софтофон. Берем софтофон, который умеет автоматически отвечать на звонок. Все входящие звонки помещаем в очередь. От туда кидаем на 1С событие, в которой указан, кому пришел звонок. При нажатии кнопки поднятия трубки, посылаем команду извлечения из очереди и соединением с номером. Софтофон автоматом поднимает трубку. Эти вопросы не относятся к компоненте. Эта реализация описана на 1001 сайте. Надеюсь, вопросов как работает астериск ко мне не будет. Я не учебный портал.

Как понять раз используется софто фон а что есть другие альтернативы для выведения звука в 1С ? Ведь 1С не поддерживает sip или pjsip

**Comment by Arsiprog** [comment]
Понял 
![image](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/45854657/5af57eab-1266-41b2-8f65-8280a1826ceb)

**Comment by Arsiprog** [comment]
http rest api  я умею хорошо а теперь с командой астерикса надо разобраться

**Comment by Arsiprog** [comment]
Пожалуйста немного направите меня я  оплачу за суету)

**Comment by korv1982** [comment]
> Как понять раз используется софто фон а что есть другие альтернативы для выведения звука в 1С ? Ведь 1С не поддерживает sip или pjsip

Да. \У меня все проекты на аппаратных телефонах. С поднятием трубки подтягивается нужная информация.

**Comment by korv1982** [comment]
> Пожалуйста немного направите меня я оплачу за суету)

Для начала нужно описать требуемую задачу. 
1. Какой дистр астериска используется
2. есть ли доступ к настройкам астериска.
3. какая конфигурация будет использоваться для работы с астериск. 
4. REST API в принципе не нужно. Если только для софтофона. моя компонента как раз и решает задачу, отфильтровать все лишнее от астера до пользователя. Там бывает 1000 событий в секунду. 1С под таким умрет. Я пробовал. 

Все это направляем на почту admin@innova-it.org. Здесь только проблемы по работе компоненты.

**Comment by Arsiprog** [comment]
ок босс все будет все  скину !

**Comment by korv1982** [comment]
> ок босс все будет все скину !

![изображение](https://github.com/korv1982/InnovaIT-Asterisk-Native/assets/11134130/a3aa73ab-b007-4613-a8e4-6b51eee3813b)

Звонилка умеет поднимать трубку. Можно использовать вторую копию моего приложения и общаться со звонилкой посредством telnet. При отправке звонка можно сразу отправить команду на снятие трубки.

**Comment by Arsiprog** [comment]
А где вторая копия приложения ? вы имеете ввиду базу 1С ? или dll файлы ?

**Comment by korv1982** [comment]
Создать ещё одну копию компоненты. И ей цепляться до телефона. Хотя это даже лишнее. Достаточно в софтофоне настроить скрипт. 
--
Отправлено из Mail.ru для Android четверг, 28 сентября 2023г., 17:35 +03:00 от Arsiprog  ***@***.*** :

**Comment by Arsiprog** [comment]
по всему инету искал а образцы скриптов phoner lite не нашел)

**Comment by Arsiprog** [comment]
Кстати я написал вам на почту)
и вообще довайте дружить мы берем на себя 1С вы по части телефонии)

**Comment by Arsiprog** [comment]
Клиентам будем продавать решения мы под любую конфу ее подправим !

**Comment by korv1982** [comment]
Да, я видел. Дальнейшую переписку предлагаю вести там. 
--
Отправлено из Mail.ru для Android четверг, 28 сентября 2023г., 17:46 +03:00 от Arsiprog  ***@***.*** :
